### PR TITLE
Minor fixes in post

### PR DESCRIPTION
**Pull request by jpherdi**
### Checklist

- [x] All included images are public domain images or their respective licenses are respected (e.g. attribution for CC-BY)
- [x] Images are reduced to around 2000px at the long edge and in jpg format

### CODE REVIEW

**Comment by jpherdi** [comment]
@The-Ludwig Could you check the screen shot? There is a black line on the right side, which looks not so nice.
And maybe we should change the title on the poster to "Bachelor-Kolloquium". It is a bit inconsistent with the website. And even though there is more than one occasion I would still say it is nice to name it in singular in general.

**Comment by maxnoe** [comment]
Das Logo sieht so aus als hätte es eine falsche Strichdicke (größerer Kreis bei gleicher Strichdicke?). Das sollte einfach das normale logo entsprechend skaliert sein.

**Review by The-Ludwig — APPROVED** [review]
Can be merged

**Comment by The-Ludwig** [comment]
@maxnoe True, I'll look into it.

**Comment by The-Ludwig** [comment]
@maxnoe A TIKZ scope with scale doesn't scale linewidth... fixed that

**Pull request merged**
