### PR TITLE
Add images of the board

### PR DESCRIPTION
**Pull request by MaxNoe**

### CODE REVIEW

**Comment by alexbirne** [comment]
I liked the idea of giving the cash auditors also credit for their work on our homepage - even if they are not part of the "every day work", we should maybe discuss (tomorrow in our meeting) if we really want to remove them completely, or maybe find alternatives, e.g. less prominent without photos of them (just one suggestion which just came to my mind)

**Comment by bixel** [comment]
Thats what I just wanted to say. Everything else looks ready for merge.

**Comment by MaxNoe** [comment]
Cash auditors belong by definition not to the board and should also not be associated with it. A page called vorstand is the wrong place.

**Comment by alexbirne** [comment]
I agree that the cash auditors don't belong to the board - however I think we should discuss if we want to remove them completely or if we want to mention them somewhere else - this could be on a different webpage (not my favourite) or e.g. in a specific section on the same webpage (not really sure about this as well) - other/better ideas welcome

**Pull request merged**
