### PR TITLE
Update gremium-html

### PR DESCRIPTION
**Pull request by ToniAJ**
Hopefully, all mistakes are eliminated by now. Jan P. H. will check :)

### Checklist

- [ ] Images are reduced to around 2000px at the long edge and in jpg format 
- [ ] No mistakes in the html Code

### CODE REVIEW

**Comment by jpherdi** [comment]
I think it is good. I just removed some unnecessary lines of code.

**Comment by jpherdi** [comment]
Why did you change Donnas picture @chrbeckm ?

**Comment by chrbeckm** [comment]
I changed the name to comply with `gremien.html` and standard file naming in that directory.

**Comment by maxnoe** [comment]
> I changed the name to comply with gremien.html and standard file naming in that directory.

I see a new file, not a rename

**Comment by maxnoe** [comment]
And 1.8 MB is way to large for a portrait that is show on a page with many portraits

**Comment by jpherdi** [comment]
@chrbeckm Could you check this again?

**Review by lena-lin — APPROVED** [review]

**Pull request merged**
